main: "jp.jyn.zabbigot.Zabbigot"
name: "Zabbigot"
version: "${project.version}"
website: "https://github.com/HimaJyun/Zabbigot"
author: '@HimaJyun'

commands:
    zabbigot:
        description: "Show status."

permissions:
    zabbigot.show:
        default: op
    zabbigot.send:
        default: op
    zabbigot.reload:
        default: op
